export default {
  pages: [
    //[VSCP-FIXED]:ADD_PAGE
    // "h5/pages/singlePage/test/index",
    // "h5/pages/IH/expressTrack/index",
    // "h5/pages/IH/paymentList/index",
    // "h5/pages/IH/Consultation/editAddress/index",
    // "h5/pages/IH/Consultation/addressList/index",
    // "h5/pages/IH/Consultation/consultation/index",
    // "h5/pages/IH/index/index4_2/index",
    // "h5/pages/IH/Consultation/pay/index",
    // "h5/pages/IH/drawboard/docdetail/index",
    "h5/pages/IH/drawboard/appointment/index",
    // "h5/pages/IH/orderList/index",
    // "h5/pages/IH/department/index",
    // "h5/pages/IH/chooseDoctor/index",
    // "h5/pages/IH/personCenter/index",
    // "h5/pages/IH/inquiryCard/index",
    // "h5/pages/IH/addUser/index",
    // "h5/pages/IH/userECard/index",
    // "h5/pages/IH/patientInfo/index",
    // "h5/pages/IH/webview/index",
    // "h5/pages/IH/result/index",
    // "h5/pages/IH/reportQuery/index",
    // "h5/pages/IH/reportDocuments/index",
    // "h5/pages/IH/bodyInfo/index",
    // "h5/pages/IH/advise/index",
    // "h5/pages/IH/adviseInfoShow/index",
    // "h5/pages/IH/doctorLogin/index",
    // "h5/pages/IH/iframeView/index",
    // "h5/pages/IH/selectTime/index",
    // "h5/pages/IH/selectDoctorTime/index",
    // "h5/pages/IH/inquiryType/index",
    // "h5/pages/IH/selectCard/index",
    // "h5/pages/IH/selectCard/index",

    // "h5/pages/ESZXYY/index/index",
    // "h5/pages/ESZXYY/IDInfo/index",
    // "h5/pages/ESZXYY/register/index",
    // "h5/pages/ESZXYY/apply/index",
    // "h5/pages/ESZXYY/applyInfo/index",
    // "h5/pages/ESZXYY/uploadIDCard/index",
    // "h5/pages/ESZXYY/notice/index",
    // "h5/pages/ESZXYY/iframeView/index",
    // "h5/pages/ESZXYY/diseaseForm/index",
    // "h5/pages/ESZXYY/confirmOrder/index",

    // "h5/pages/THYYYDC/selectAddress/index",
    // "h5/pages/THYYYDC/settlement/index",
    // "h5/pages/THYYYDC/order/index",
    // "h5/pages/THYYYDC/orderForm/index",//订单记录
    // "h5/pages/THYYYDC/addAddress/index",
    // "h5/pages/THYYYDC/selectType/index",//首页
    // "h5/pages/THYYYDC/loading/index",

    // "h5/pages/TJXRMYY/HTMLInfoShow/index",
    // "h5/pages/TJXRMYY/registrationArgeement/index",
    // "h5/pages/TJXRMYY/bodyinfoShow/index",
    // "h5/pages/TJXRMYY/bodySelect/index",
    // "h5/pages/TJXRMYY/bodyInfo/index",
    // "h5/pages/TJXRMYY/indexNew/index",
    // "h5/pages/TJXRMYY/optionList/index",
    // "h5/pages/TJXRMYY/infoShow/index",
    // "h5/pages/TJXRMYY/loading/index",
    // "h5/pages/TJXRMYY/register/index",
    // "h5/pages/TJXRMYY/itemInfo/index",
    // "h5/pages/TJXRMYY/itemList/index",
    // "h5/pages/TJXRMYY/submitForm/index",
    // "h5/pages/TJXRMYY/userECard/index",
    // "h5/pages/TJXRMYY/feedback/index",
    // "h5/pages/TJXRMYY/satisfactionSurvey/index",
    // "h5/pages/TJXRMYY/surveyList/index",
    // "h5/pages/TJXRMYY/evaluate/index",
    // "h5/pages/TJXRMYY/patientInfo/index",
    // "h5/pages/TJXRMYY/expenceList/index",
    // "h5/pages/TJXRMYY/login/index",
    // "h5/pages/TJXRMYY/cardLogin/index",
    // "h5/pages/TJXRMYY/reportQuery/index",
    // "h5/pages/TJXRMYY/appDetail/index",

    // "h5/pages/TJXRMYY/reportDocuments/index",
    // "h5/pages/TJXRMYY/demo/index",

    // "h5/pages/TJXRMYY/reportDetails/index",
    // "h5/pages/TJXRMYY/NATType/index",
    // "h5/pages/TJXRMYY/NATType_01/index",
    // "h5/pages/TJXRMYY/paymentList/index",
    // "h5/pages/TJXRMYY/paymentList02/index",
    // "h5/pages/TJXRMYY/result/index",
    // "h5/pages/TJXRMYY/confirmInfo/index",
    // "h5/pages/TJXRMYY/doctorSelect/index",
    // "h5/pages/TJXRMYY/deptSelect/index",
    // "h5/pages/TJXRMYY/patientForm/index",
    // "h5/pages/TJXRMYY/patientIDcard/index",
    // "h5/pages/TJXRMYY/personalCenter/index",
    // "h5/pages/TJXRMYY/hospitalPay/index",
    // "h5/pages/TJXRMYY/index/index",
    // "h5/pages/TJXRMYY/tableInfo/index"
    // "h5/pages/TJXRMYY/selectTime/index"
  ],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#fff",
    navigationBarTitleText: "",
    navigationBarTextStyle: "black"
  },
  // subPackages:[
  //   {
  //     root: 'h5/pages/ESZXYY/',
  //     pages: [
  //       "index/index",
  //       "IDInfo/index",
  //       "register/index",
  //       "apply/index",
  //       "applyInfo/index",
  //       "uploadIDCard/index",
  //       "notice/index",
  //       "iframeView/index",
  //       "diseaseForm/index",
  //       "confirmOrder/index",
  //     ],
  //   },
  //   {
  //     root: 'h5/pages/IH/',
  //     pages: [
  //       "eHealthCard/index",
  //       "expressTrack/index",
  //       "paymentList/index",
  //       "Consultation/editAddress/index",
  //       "Consultation/addressList/index",
  //       "Consultation/consultation/index",
  //       "index/index4/index",
  //       "Consultation/pay/index",
  //       "drawboard/docdetail/index",
  //       "drawboard/appointment/index",
  //       "orderList/index",
  //       "department/index",
  //       "chooseDoctor/index",
  //       "personCenter/index",
  //       "inquiryCard/index",
  //       "addUser/index",
  //       "userECard/index",
  //       "patientInfo/index",
  //       "webview/index",
  //       "result/index",
  //       "reportQuery/index",
  //       "reportDocuments/index",
  //       "bodyInfo/index",
  //       "advise/index",
  //       "adviseInfoShow/index",
  //       "doctorLogin/index",
  //       "iframeView/index",
  //       "selectTime/index",
  //       "inquiryType/index",
  //     ],
  //   },
  //   // {
  //   //   root: 'h5/pages/SCWJYY/',
  //   //   pages: [
  //   //
  //   //   ],
  //   // },
  //   {
  //     root: 'h5/pages/THYYYDC/',
  //     pages: [
  //       "selectAddress/index",
  //       "settlement/index",
  //       "order/index",
  //       "orderForm/index",//订单记录
  //       "addAddress/index",
  //       "selectType/index",//首页
  //       "loading/index"
  //     ],
  //   },
  //   {
  //     root: 'h5/pages/TJXRMYY/',
  //     pages: [
  //       "HTMLInfoShow/index",
  //       "registrationArgeement/index",
  //       "bodyinfoShow/index",
  //       "bodySelect/index",
  //       "bodyInfo/index",
  //       "indexNew/index",
  //       "optionList/index",
  //       "infoShow/index",
  //       "loading/index",
  //       "register/index",
  //       "itemInfo/index",
  //       "itemList/index",
  //       "submitForm/index"
  //     ],
  //   },
  // ],
  // plugins: {
  //   healthCardPlugins: {
  //     version: "3.19.2",
  //     provider: "wxee969de81bba9a45"
  //   }
  // },
};
